# Generated by Django 4.0.3 on 2022-04-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='aplication_link',
            new_name='application_link',
        ),
    ]
